### ISSUE TITLE
IEEEmadC - Submission

### ISSUE THREAD

**Issue by SangramChavan** [alex8530/IEEE_MADC_2019_Android_Learning_Children_App#1]
Your apps looks good, nice UI. Can you please add a table to your redme? sharing an example below.

Example: App Name (Hyperlink to executable file) | Repo name (Hyperlink to repo) | description (short description of app in few words) | Choose any license e.g. MIT (Hyperlink to Licence)| UK (Location)| Name of members (Hyperlink to Github profiles that contributed to the project) |

**Comment by alex8530** [comment]
yes sure .. i will do that. thx

**Comment by alex8530** [comment]
I add the table... can you check it > so i know that everything is OK  then close this issue.

**Comment by SangramChavan** [comment]
You missed this 

App Name (Hyperlink to executable file) | Repo name (Hyperlink to repo) | description (short description of app in few words) | Choose any license e.g. MIT (Hyperlink to Licence)| UK (Location)| Name of members (Hyperlink to Github profiles that contributed to the project) |

not the content table.

**Comment by alex8530** [comment]
still confused about what i should to do .. can you give me an example from my readMe ?

**Comment by SangramChavan** [comment]
Following with links:
<img width="1055" alt="Screenshot 2019-12-20 at 9 39 35 PM" src="https://user-images.githubusercontent.com/9999729/71294745-4db1dc80-2371-11ea-9ed4-0b271b461a0b.png">

**Comment by alex8530** [comment]
have done>> thank you
